# Website's icon url.
favicon: /favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:
  text: Afwing Backup

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  飞机图介: /categories/飞机图介
  鹰之利爪: /categories/鹰之利爪
  航空百科: /categories/航空百科
  战史战例: /categories/战史战例
  名机靓影: /categories/名机靓影
  旧站资源: /categories/旧站资源

# Search plugin settings.
search:
  type: google-cse
  cx: 017507374549931397585%3Ajhlgzbg4jti

# Navigation bar toc settings
toc: true

# Share plugin settings.
share:
  type:
  install_url:

# Comment plugin settings.
comment:
  type:
  shortname:

# Other plugins and their settings.
plugins:
  mathjax: false
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:


# Links at the bottom of the page.
footer_links:
  空军之翼: http://www.kongyiwang.com/
